#version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: obsrv_user
      POSTGRES_PASSWORD: obsrv123
      POSTGRES_DB: obsrv_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U obsrv_user -d obsrv_db"]
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: obsrv_user
      POSTGRES_PASSWORD: obsrv123
      POSTGRES_DB: obsrv_db
      POSTGRES_HOST: db
      DATABASE_URL: postgresql+asyncpg://obsrv_user:obsrv123@db:5432/obsrv_db
    ports:
      - "8000:8000"

volumes:
  pgdata: